- hosts: workstation
  gather_facts: false
  
  tasks:
  - name: OpenStack servers
    os_server_facts:
     cloud: openstack
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke

  - name: Check webserver for correct response
    uri:
      url: "http://{{item.public_v4}}"
      return_content: yes
    until: '"Welcome" in result.content'
    retries: 10
    delay: 1
    register: result
    delegate_to: localhost
