---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: Add multiple repositories into the same file (1/4)
  yum_repository:
    name: rhel-7-server-rpms
    description: Red Hat Enterprise Linux 7
    file: hwrepos
    baseurl: http://admin.na.shared.opentlc.com/repos/tower//3.5.3-1/rhel-7-server-rpms
    gpgcheck: no

- name: Add multiple repositories into the same file (2/4)
  yum_repository:
    name: rhel-7-server-rh-common-rpms
    description: Red Hat Enterprise Linux 7 Common
    file: hwrepos
    baseurl: http://admin.na.shared.opentlc.com/repos/tower//3.5.3-1/rhel-7-server-rh-common-rpms
    gpgcheck: no

- name: Add multiple repositories into the same file (3/4)
  yum_repository:
    name: rhel-7-server-extras-rpms
    description: Red Hat Enterprise Linux 7 Extras
    file: hwrepos
    baseurl: http://admin.na.shared.opentlc.com/repos/tower//3.5.3-1/rhel-7-server-extras-rpms
    gpgcheck: no
    
- name: Add multiple repositories into the same file (4/5)
  yum_repository:
    name: rhel-7-server-optional-rpms
    description: Red Hat Enterprise Linux 7 optional
    file: hwrepos
    baseurl: http://admin.na.shared.opentlc.com/repos/tower//3.5.3-1/rhel-7-server-optional-rpms
    gpgcheck: no

- name: Add multiple repositories into the same file (5/5)
  yum_repository:
    name: rhel-7-server-rhscl-rpms
    description: Red Hat Enterprise Linux 7 optional
    file: hwrepos
    baseurl: http://admin.na.shared.opentlc.com/repos/tower//3.5.3-1/rhel-server-rhscl-7-rpms
    gpgcheck: no

- name: Add epel repositories 
  yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux 7
    file: epel
    baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
    mirrorlist: http://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
    gpgcheck: no

- name: install base tools and packages
  yum:
    name: git
    state: latest
