---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
    yum_repositoriy:
      name: rhel-repo
      description: “Repo for hosts in testing”
      baseurl: “http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo”
      gpgcheck: yes
      gpgkey: file:///etc/pki/gpg-key 
      
- name: install base tools and packages
    yum:
      name: git
      state: latest
